"""add project

Revision ID: 1cce56c440e4
Revises: 
Create Date: 2025-11-21 07:58:58.978269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1cce56c440e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'donations', 'projects', ['project_id'], ['id'])
    op.drop_column('donations', 'recipient')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('recipient', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.drop_constraint(None, 'donations', type_='foreignkey')
    # ### end Alembic commands ###
